/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.altessmann.RetaguardaAdministrativoPessoal;

/**
 *
 * @author EngComp
 */
public class CadastroFornecedorNew extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedorNew
     */
    public CadastroFornecedorNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboSelecionaTipoPesquisa = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonGravar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonNovo3 = new javax.swing.JButton();
        TextValorCusto127 = new javax.swing.JTextField();
        LabelValorCus112 = new javax.swing.JLabel();
        TextValorCusto128 = new javax.swing.JTextField();
        LabelValorCus113 = new javax.swing.JLabel();
        TextValorCusto129 = new javax.swing.JTextField();
        jButtonNovo4 = new javax.swing.JButton();
        TextValorCusto130 = new javax.swing.JTextField();
        TextValorCusto131 = new javax.swing.JTextField();
        TextValorCusto132 = new javax.swing.JTextField();
        LabelValorCus114 = new javax.swing.JLabel();
        jButtonNovo5 = new javax.swing.JButton();
        LabelValorCus115 = new javax.swing.JLabel();
        TextValorCusto133 = new javax.swing.JTextField();
        TextValorCusto134 = new javax.swing.JTextField();
        jButtonNovo6 = new javax.swing.JButton();
        LabelValorCus49 = new javax.swing.JLabel();
        DateCadastro3 = new com.toedter.calendar.JDateChooser();
        TextValorCusto137 = new javax.swing.JTextField();
        LabelValorCus117 = new javax.swing.JLabel();
        jComboSelecionaTipoPesquisa10 = new javax.swing.JComboBox();
        LabelValorCus50 = new javax.swing.JLabel();
        LabelValorCus51 = new javax.swing.JLabel();
        jComboSelecionaTipoPesquisa11 = new javax.swing.JComboBox();
        jComboSelecionaTipoPesquisa12 = new javax.swing.JComboBox();
        LabelValorCus52 = new javax.swing.JLabel();
        LabelValorCus53 = new javax.swing.JLabel();
        jComboSelecionaTipoPesquisa13 = new javax.swing.JComboBox();
        TextValorCusto138 = new javax.swing.JTextField();
        LabelValorCus118 = new javax.swing.JLabel();
        TextValorCusto139 = new javax.swing.JTextField();
        LabelValorCus119 = new javax.swing.JLabel();
        DateCadastro4 = new com.toedter.calendar.JDateChooser();
        LabelValorCus54 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AreaObs = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        TextValorCusto140 = new javax.swing.JTextField();
        LabelValorCus120 = new javax.swing.JLabel();
        TextValorCusto141 = new javax.swing.JTextField();
        LabelValorCus121 = new javax.swing.JLabel();
        TextValorCusto142 = new javax.swing.JTextField();
        LabelValorCus122 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Atividade", "Situação", "Desde", "Data Cadastro", "Localização"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente.setRowHeight(20);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCliente);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setMinWidth(300);
            jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(300);
            jTableCliente.getColumnModel().getColumn(0).setMaxWidth(300);
            jTableCliente.getColumnModel().getColumn(1).setMinWidth(250);
            jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableCliente.getColumnModel().getColumn(1).setMaxWidth(250);
            jTableCliente.getColumnModel().getColumn(2).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(3).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(4).setMinWidth(100);
            jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
            jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        jTextPesquisar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        jTextPesquisar.setText("Selecione uma das opções de pesquisa ...");
        jTextPesquisar.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextPesquisar.setPreferredSize(new java.awt.Dimension(500, 25));
        jTextPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PesquisarCli.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar Fornecedor");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButton2.setText("Adicionar ");
        jButton2.setToolTipText("");
        jButton2.setMaximumSize(new java.awt.Dimension(300, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrircli.png"))); // NOI18N
        jButton3.setText("Listar Fornecedores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboSelecionaTipoPesquisa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Situação" }));
        jComboSelecionaTipoPesquisa.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)
                        .addGap(3, 3, 3)
                        .addComponent(jButton3)
                        .addGap(3, 3, 3)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboSelecionaTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("  Pesquisar Fornecedor  ", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Fornecedor  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo.setText("Novo Fornecedor");
        jButtonNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar24x24.png"))); // NOI18N
        jButtonEditar.setText("Editar Cadastro");
        jButtonEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close24x24.png"))); // NOI18N
        jButtonExcluir.setText("Excluir Cadastro");
        jButtonExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save24x24.png"))); // NOI18N
        jButtonGravar.setText("Salvar Cadastro");
        jButtonGravar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonGravar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel24x24.png"))); // NOI18N
        jButtonGravar1.setText("Cancelar");
        jButtonGravar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonNovo)
                .addGap(3, 3, 3)
                .addComponent(jButtonEditar)
                .addGap(3, 3, 3)
                .addComponent(jButtonExcluir)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Detalhes  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo3ActionPerformed(evt);
            }
        });

        TextValorCusto127.setEditable(false);
        TextValorCusto127.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto127.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto127.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto127.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto127ActionPerformed(evt);
            }
        });

        LabelValorCus112.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus112.setText("Pessoa:");

        TextValorCusto128.setEditable(false);
        TextValorCusto128.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto128.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto128.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto128.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto128ActionPerformed(evt);
            }
        });

        LabelValorCus113.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus113.setText("Situação:");

        TextValorCusto129.setEditable(false);
        TextValorCusto129.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto129.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto129.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto129.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto129ActionPerformed(evt);
            }
        });

        jButtonNovo4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo4ActionPerformed(evt);
            }
        });

        TextValorCusto130.setEditable(false);
        TextValorCusto130.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto130.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto130.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto130.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto130ActionPerformed(evt);
            }
        });

        TextValorCusto131.setEditable(false);
        TextValorCusto131.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto131.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto131.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto131.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto131ActionPerformed(evt);
            }
        });

        TextValorCusto132.setEditable(false);
        TextValorCusto132.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto132.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto132.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto132.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto132ActionPerformed(evt);
            }
        });

        LabelValorCus114.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus114.setText("Atividade:");

        jButtonNovo5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo5ActionPerformed(evt);
            }
        });

        LabelValorCus115.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus115.setText("Conta Contabil:");

        TextValorCusto133.setEditable(false);
        TextValorCusto133.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto133.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto133.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto133.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto133ActionPerformed(evt);
            }
        });

        TextValorCusto134.setEditable(false);
        TextValorCusto134.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto134.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto134.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto134.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto134ActionPerformed(evt);
            }
        });

        jButtonNovo6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo6ActionPerformed(evt);
            }
        });

        LabelValorCus49.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus49.setText("Desde:");

        DateCadastro3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DateCadastro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png")));

        TextValorCusto137.setEditable(false);
        TextValorCusto137.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto137.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto137.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto137.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto137ActionPerformed(evt);
            }
        });

        LabelValorCus117.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus117.setText("Conta Remetente:");

        jComboSelecionaTipoPesquisa10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa10.setToolTipText("");

        LabelValorCus50.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus50.setText("Gera Faturamento:");

        LabelValorCus51.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus51.setText("Optante Simples Nacional:");

        jComboSelecionaTipoPesquisa11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa11.setToolTipText("");

        jComboSelecionaTipoPesquisa12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa12.setToolTipText("");

        LabelValorCus52.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus52.setText("Localização:");

        LabelValorCus53.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus53.setText("Sofre Retenção:");

        jComboSelecionaTipoPesquisa13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa13.setToolTipText("");

        TextValorCusto138.setEditable(false);
        TextValorCusto138.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto138.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto138.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto138.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto138.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto138ActionPerformed(evt);
            }
        });

        LabelValorCus118.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus118.setText("Prazo Medio Entrega:");

        TextValorCusto139.setEditable(false);
        TextValorCusto139.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto139.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto139.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto139.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto139ActionPerformed(evt);
            }
        });

        LabelValorCus119.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus119.setText("Num Dias Primeiro Vencimento:");

        DateCadastro4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DateCadastro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png")));

        LabelValorCus54.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus54.setText("Data Cadastro:");

        AreaObs.setColumns(1);
        AreaObs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AreaObs.setLineWrap(true);
        AreaObs.setRows(1);
        jScrollPane4.setViewportView(AreaObs);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel28.setText("Observação:");

        TextValorCusto140.setEditable(false);
        TextValorCusto140.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto140.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto140.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto140.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto140ActionPerformed(evt);
            }
        });

        LabelValorCus120.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus120.setText("Num Dias Intervalo:");

        TextValorCusto141.setEditable(false);
        TextValorCusto141.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto141.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto141.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto141.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto141.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto141ActionPerformed(evt);
            }
        });

        LabelValorCus121.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus121.setText("Quantidade Parcelas:");

        TextValorCusto142.setEditable(false);
        TextValorCusto142.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto142.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto142.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto142.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto142.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto142ActionPerformed(evt);
            }
        });

        LabelValorCus122.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus122.setText("Cheque Nominal A:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelValorCus112)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TextValorCusto127, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButtonNovo3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextValorCusto128, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelValorCus113)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TextValorCusto129, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButtonNovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextValorCusto130, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelValorCus114)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TextValorCusto132, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButtonNovo5)))
                        .addGap(5, 5, 5)
                        .addComponent(TextValorCusto131, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DateCadastro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelValorCus49)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LabelValorCus115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextValorCusto133, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(3, 3, 3)
                                    .addComponent(jButtonNovo6))
                                .addComponent(TextValorCusto138, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelValorCus118))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TextValorCusto134, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateCadastro4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelValorCus54)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TextValorCusto139, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelValorCus119, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(LabelValorCus120)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(TextValorCusto140, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextValorCusto137, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelValorCus117))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelValorCus50)
                                            .addComponent(jComboSelecionaTipoPesquisa10, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelValorCus51, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(jComboSelecionaTipoPesquisa11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus121)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TextValorCusto141, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelValorCus52, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboSelecionaTipoPesquisa12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelValorCus53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jComboSelecionaTipoPesquisa13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus122)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TextValorCusto142, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonNovo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextValorCusto132, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextValorCusto131, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelValorCus112)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNovo3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(TextValorCusto127, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextValorCusto128, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelValorCus113)
                            .addComponent(LabelValorCus114))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNovo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextValorCusto129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextValorCusto130, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelValorCus115)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNovo6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(TextValorCusto133, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelValorCus54)
                        .addGap(1, 1, 1)
                        .addComponent(DateCadastro4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextValorCusto134, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelValorCus49)
                            .addComponent(LabelValorCus117, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelValorCus50))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextValorCusto137, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(DateCadastro3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboSelecionaTipoPesquisa10)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelValorCus51)
                            .addComponent(LabelValorCus52)
                            .addComponent(LabelValorCus53))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboSelecionaTipoPesquisa11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboSelecionaTipoPesquisa12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboSelecionaTipoPesquisa13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelValorCus118, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelValorCus119, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelValorCus120, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextValorCusto140, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextValorCusto141, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextValorCusto139, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextValorCusto138, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelValorCus121, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TextValorCusto142, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelValorCus122, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Fornecedor Detalhes  ", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPesquisarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {           // adiciona as tabelas de acordo com a String selecionada no jComboBox
            //
            //            String terminal = jComboSelecionaTipoPesquisa.getSelectedItem() + ""; // transforma o jComboBox em uma String
            //            try {
                //                if (terminal.equals("Código")) {    // compara para ver se a String e o codigo
                    //                    if (!clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).isEmpty()) { //testa para ver se existem clientes com o cpodigo informado
                        //                        for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                            //                            model.addRow(new String[]{jTextPesquisar.getText() + "", clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getNome(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getLogradouro(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getT1(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getStatus()});
                            //                        }
                        //                    } else {
                        //                        JOptionPane.showMessageDialog(null, "Não existem clientes com o código " + jTextPesquisar.getText() + " cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                        //                    }
                    //                }
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
                //
                //            }
            //            if (terminal.equals("Nome")) {
                //                if (!clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getCodigo() + "", clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getNome(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getLogradouro(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getT1(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //                }
                //                //clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(0).getCodigo();
                //            }
            //            if (terminal.equals("RG")) {
                //                if (!clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").isEmpty()) {
                    //                    System.out.println(clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome());
                    //
                    //                    model.addRow(new String[]{clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getCodigo() + "", clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getLogradouro(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getT1(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getStatus()});
                    //
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o RG '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "");
                //            }
            //
            //            if (terminal.equals("CPF")) {
                //
                //                if (!clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getCodigo() + "", clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getNome(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getLogradouro(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getT1(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o CPF '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null);
                //            }
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {
            //            if (!clienteDAO.getCliente("", null, null).isEmpty()) {
                //                for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                    //                    model.addRow(new String[]{clienteDAO.getCliente().get(i).getCodigo() + "", clienteDAO.getCliente().get(i).getNome(), clienteDAO.getCliente().get(i).getLogradouro(), clienteDAO.getCliente().get(i).getT1(), clienteDAO.getCliente().get(i).getStatus()});
                    //                }
                //            } else {
                //                JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                //            }
            //        } catch (SQLException ex) {
            //            System.out.println(ex);
            //        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        //        this.jButtonNovo.setEnabled(false);
        //        this.ativaCampo();
        //        this.limpaCampo();
        //        this.jButtonGravar.setEnabled(true);
        //        this.setNovoCodigo();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //        this.ativaCampo();
        //        this.jButtonGravar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        //        String terminal = this.jComboGrupo.getSelectedItem() + "";
        //        char[] a = terminal.toCharArray();
        //        int posicao = 0;
        //        for (int i = 0; i < terminal.length(); i++) {
            //            if (a[i] == '-') {
                //                posicao = i;
                //            }
            //        }
        //        int codigoGrupo = Integer.parseInt(terminal.substring(0, posicao));
        //        try {
            //            if (subGrupoDAO.ContaCod(Integer.parseInt(jTextCodigo.getText())) == 0) {
                //                subGrupoDAO.setSubGrupo(jTextDescricao.getText() + "", codigoGrupo, subGrupoBean.getTentativas());
                //            } else {
                //                subGrupoDAO.atualizaSubGrupo(Integer.parseInt(jTextCodigo.getText()), jTextDescricao.getText() + "", codigoGrupo, subGrupoBean.getTentativas());
                //            }
            //            this.desativaCampo();
            //            this.jButtonGravar.setEnabled(false);
            //            this.jButtonNovo.setEnabled(true);
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravar1ActionPerformed

    private void jButtonNovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo3ActionPerformed

    private void TextValorCusto127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto127ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto127ActionPerformed

    private void TextValorCusto128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto128ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto128ActionPerformed

    private void TextValorCusto129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto129ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto129ActionPerformed

    private void jButtonNovo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo4ActionPerformed

    private void TextValorCusto130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto130ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto130ActionPerformed

    private void TextValorCusto131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto131ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto131ActionPerformed

    private void TextValorCusto132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto132ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto132ActionPerformed

    private void jButtonNovo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo5ActionPerformed

    private void TextValorCusto133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto133ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto133ActionPerformed

    private void TextValorCusto134ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto134ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto134ActionPerformed

    private void jButtonNovo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo6ActionPerformed

    private void TextValorCusto137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto137ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto137ActionPerformed

    private void TextValorCusto138ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto138ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto138ActionPerformed

    private void TextValorCusto139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto139ActionPerformed

    private void TextValorCusto140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto140ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto140ActionPerformed

    private void TextValorCusto141ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto141ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto141ActionPerformed

    private void TextValorCusto142ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto142ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto142ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedorNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaObs;
    private com.toedter.calendar.JDateChooser DateCadastro3;
    private com.toedter.calendar.JDateChooser DateCadastro4;
    private javax.swing.JLabel LabelValorCus112;
    private javax.swing.JLabel LabelValorCus113;
    private javax.swing.JLabel LabelValorCus114;
    private javax.swing.JLabel LabelValorCus115;
    private javax.swing.JLabel LabelValorCus117;
    private javax.swing.JLabel LabelValorCus118;
    private javax.swing.JLabel LabelValorCus119;
    private javax.swing.JLabel LabelValorCus120;
    private javax.swing.JLabel LabelValorCus121;
    private javax.swing.JLabel LabelValorCus122;
    private javax.swing.JLabel LabelValorCus49;
    private javax.swing.JLabel LabelValorCus50;
    private javax.swing.JLabel LabelValorCus51;
    private javax.swing.JLabel LabelValorCus52;
    private javax.swing.JLabel LabelValorCus53;
    private javax.swing.JLabel LabelValorCus54;
    private javax.swing.JTextField TextValorCusto127;
    private javax.swing.JTextField TextValorCusto128;
    private javax.swing.JTextField TextValorCusto129;
    private javax.swing.JTextField TextValorCusto130;
    private javax.swing.JTextField TextValorCusto131;
    private javax.swing.JTextField TextValorCusto132;
    private javax.swing.JTextField TextValorCusto133;
    private javax.swing.JTextField TextValorCusto134;
    private javax.swing.JTextField TextValorCusto137;
    private javax.swing.JTextField TextValorCusto138;
    private javax.swing.JTextField TextValorCusto139;
    private javax.swing.JTextField TextValorCusto140;
    private javax.swing.JTextField TextValorCusto141;
    private javax.swing.JTextField TextValorCusto142;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonGravar1;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonNovo3;
    private javax.swing.JButton jButtonNovo4;
    private javax.swing.JButton jButtonNovo5;
    private javax.swing.JButton jButtonNovo6;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa10;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa11;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa12;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa13;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextPesquisar;
    // End of variables declaration//GEN-END:variables
}
