/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.altessmann.RetaguardaAdministrativoPessoal;

/**
 *
 * @author Ritiele Aldeburg
 */
public class SindicatoNew extends javax.swing.JFrame {

    /**
     * Creates new form SindicatoNew
     */
    public SindicatoNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCliente2 = new javax.swing.JTable();
        jTextPesquisar2 = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonGravar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        LabelValorCus112 = new javax.swing.JLabel();
        TextValorCusto128 = new javax.swing.JTextField();
        LabelValorCus115 = new javax.swing.JLabel();
        TextValorCusto133 = new javax.swing.JTextField();
        TextValorCusto134 = new javax.swing.JTextField();
        jButtonNovo6 = new javax.swing.JButton();
        LabelValorCus49 = new javax.swing.JLabel();
        DateCadastro3 = new com.toedter.calendar.JDateChooser();
        TextValorCusto137 = new javax.swing.JTextField();
        LabelValorCus117 = new javax.swing.JLabel();
        jComboSelecionaTipoPesquisa11 = new javax.swing.JComboBox();
        TextValorCusto138 = new javax.swing.JTextField();
        LabelValorCus118 = new javax.swing.JLabel();
        LabelValorCus123 = new javax.swing.JLabel();
        TextValorCusto143 = new javax.swing.JTextField();
        TextValorCusto144 = new javax.swing.JTextField();
        LabelValorCus124 = new javax.swing.JLabel();
        TextValorCusto145 = new javax.swing.JTextField();
        LabelValorCus125 = new javax.swing.JLabel();
        TextValorCusto146 = new javax.swing.JTextField();
        LabelValorCus126 = new javax.swing.JLabel();
        TextValorCusto147 = new javax.swing.JTextField();
        LabelValorCus127 = new javax.swing.JLabel();
        LabelValorCus128 = new javax.swing.JLabel();
        TextValorCusto148 = new javax.swing.JTextField();
        LabelValorCus129 = new javax.swing.JLabel();
        TextValorCusto149 = new javax.swing.JTextField();
        TextValorCusto150 = new javax.swing.JTextField();
        LabelValorCus130 = new javax.swing.JLabel();
        LabelValorCus131 = new javax.swing.JLabel();
        TextValorCusto151 = new javax.swing.JTextField();
        LabelValorCus132 = new javax.swing.JLabel();
        TextValorCusto152 = new javax.swing.JTextField();
        LabelValorCus133 = new javax.swing.JLabel();
        TextValorCusto153 = new javax.swing.JTextField();
        LabelValorCus134 = new javax.swing.JLabel();
        LabelValorCus135 = new javax.swing.JLabel();
        TextValorCusto154 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableCliente2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableCliente2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Logradouro", "Numero", "Bairro", "Uf", "Fone1", "Fone2", "Email", "Tipo Sindicato", "Data Base"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente2.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        jTableCliente2.setMinimumSize(new java.awt.Dimension(770, 800));
        jTableCliente2.setRowHeight(20);
        jTableCliente2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableCliente2);

        jTextPesquisar2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextPesquisar2.setForeground(new java.awt.Color(153, 153, 153));
        jTextPesquisar2.setText("Selecione uma das opções de pesquisa ...");
        jTextPesquisar2.setMaximumSize(new java.awt.Dimension(1000, 10000));
        jTextPesquisar2.setPreferredSize(new java.awt.Dimension(500, 25));
        jTextPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisar2ActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PesquisarCli.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar ");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButton2.setText("Adicionar ");
        jButton2.setToolTipText("");
        jButton2.setMaximumSize(new java.awt.Dimension(300, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrircli.png"))); // NOI18N
        jButton3.setText("Listar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextPesquisar2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonPesquisar)
                        .addGap(3, 3, 3)
                        .addComponent(jButton3)
                        .addGap(3, 3, 3)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jTabbedPane3.addTab("  Pesquisar Sindicato  ", jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Sindicato  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jButtonNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo.setText("Novo Sindicato");
        jButtonNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar24x24.png"))); // NOI18N
        jButtonEditar.setText("Editar Cadastro");
        jButtonEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close24x24.png"))); // NOI18N
        jButtonExcluir.setText("Excluir Cadastro");
        jButtonExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save24x24.png"))); // NOI18N
        jButtonGravar.setText("Salvar Cadastro");
        jButtonGravar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonGravar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel24x24.png"))); // NOI18N
        jButtonGravar1.setText("Cancelar");
        jButtonGravar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonNovo)
                .addGap(3, 3, 3)
                .addComponent(jButtonEditar)
                .addGap(3, 3, 3)
                .addComponent(jButtonExcluir)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar)
                .addGap(3, 3, 3)
                .addComponent(jButtonGravar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Detalhes  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        LabelValorCus112.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus112.setText("Nome:");

        TextValorCusto128.setEditable(false);
        TextValorCusto128.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto128.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto128.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto128.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto128ActionPerformed(evt);
            }
        });

        LabelValorCus115.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus115.setText("Conta Contabil:");

        TextValorCusto133.setEditable(false);
        TextValorCusto133.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto133.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto133.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto133.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto133ActionPerformed(evt);
            }
        });

        TextValorCusto134.setEditable(false);
        TextValorCusto134.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto134.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto134.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto134.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto134ActionPerformed(evt);
            }
        });

        jButtonNovo6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add2.png"))); // NOI18N
        jButtonNovo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNovo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo6ActionPerformed(evt);
            }
        });

        LabelValorCus49.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus49.setText("Data Base:");

        DateCadastro3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DateCadastro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png")));

        TextValorCusto137.setEditable(false);
        TextValorCusto137.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto137.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto137.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto137.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto137ActionPerformed(evt);
            }
        });

        LabelValorCus117.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus117.setText("Codigo Banco:");

        jComboSelecionaTipoPesquisa11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboSelecionaTipoPesquisa11.setToolTipText("");

        TextValorCusto138.setEditable(false);
        TextValorCusto138.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto138.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto138.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto138.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto138.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto138ActionPerformed(evt);
            }
        });

        LabelValorCus118.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus118.setText("Logradouro:");

        LabelValorCus123.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus123.setText("Codigo Agencia:");

        TextValorCusto143.setEditable(false);
        TextValorCusto143.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto143.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto143.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto143.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto143.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto143ActionPerformed(evt);
            }
        });

        TextValorCusto144.setEditable(false);
        TextValorCusto144.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto144.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto144.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto144.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto144.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto144ActionPerformed(evt);
            }
        });

        LabelValorCus124.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus124.setText("Conta Banco:");

        TextValorCusto145.setEditable(false);
        TextValorCusto145.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto145.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto145.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto145.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto145.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto145ActionPerformed(evt);
            }
        });

        LabelValorCus125.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus125.setText("Codigo Cedente:");

        TextValorCusto146.setEditable(false);
        TextValorCusto146.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto146.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto146.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto146.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto146ActionPerformed(evt);
            }
        });

        LabelValorCus126.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus126.setText("Numero:");

        TextValorCusto147.setEditable(false);
        TextValorCusto147.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto147.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto147.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto147.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto147.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto147ActionPerformed(evt);
            }
        });

        LabelValorCus127.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus127.setText("Bairro:");

        LabelValorCus128.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus128.setText("Uf:");

        TextValorCusto148.setEditable(false);
        TextValorCusto148.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto148.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto148.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto148.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto148.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto148ActionPerformed(evt);
            }
        });

        LabelValorCus129.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus129.setText("Municipio Ibge:");

        TextValorCusto149.setEditable(false);
        TextValorCusto149.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto149.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto149.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto149.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto149.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto149ActionPerformed(evt);
            }
        });

        TextValorCusto150.setEditable(false);
        TextValorCusto150.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto150.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto150.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto150.setText("5332481203");
        TextValorCusto150.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto150ActionPerformed(evt);
            }
        });

        LabelValorCus130.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus130.setText("Fone1:");

        LabelValorCus131.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus131.setText("Fone2:");

        TextValorCusto151.setEditable(false);
        TextValorCusto151.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto151.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto151.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto151.setText("5332481203");
        TextValorCusto151.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto151.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto151ActionPerformed(evt);
            }
        });

        LabelValorCus132.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus132.setText("Tipo Sindicato:");

        TextValorCusto152.setEditable(false);
        TextValorCusto152.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto152.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto152.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto152.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto152.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto152ActionPerformed(evt);
            }
        });

        LabelValorCus133.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus133.setText("Piso Salarial:");

        TextValorCusto153.setEditable(false);
        TextValorCusto153.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto153.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto153.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto153.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto153.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto153ActionPerformed(evt);
            }
        });

        LabelValorCus134.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus134.setText("Cnpj:");

        LabelValorCus135.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelValorCus135.setText("Email:");

        TextValorCusto154.setEditable(false);
        TextValorCusto154.setBackground(new java.awt.Color(255, 255, 255));
        TextValorCusto154.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        TextValorCusto154.setForeground(new java.awt.Color(153, 153, 153));
        TextValorCusto154.setMaximumSize(new java.awt.Dimension(1000, 10000));
        TextValorCusto154.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorCusto154ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextValorCusto154, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextValorCusto128, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto133, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(3, 3, 3)
                                        .addComponent(jButtonNovo6))
                                    .addComponent(LabelValorCus118)
                                    .addComponent(LabelValorCus117)
                                    .addComponent(TextValorCusto137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus124, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto144, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(LabelValorCus125)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(TextValorCusto145, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(TextValorCusto134, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus130, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto150, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextValorCusto151, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(LabelValorCus131, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(LabelValorCus132))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jComboSelecionaTipoPesquisa11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DateCadastro3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(TextValorCusto138, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus126, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto146, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus127, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto147, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValorCus128, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextValorCusto148, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelValorCus129, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextValorCusto149, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TextValorCusto152, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelValorCus133, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelValorCus134, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextValorCusto153, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelValorCus112)
                            .addComponent(LabelValorCus135))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(LabelValorCus133, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(TextValorCusto152, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(LabelValorCus112)
                        .addGap(1, 1, 1)
                        .addComponent(TextValorCusto128, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(LabelValorCus115)
                                .addGap(1, 1, 1)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonNovo6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                    .addComponent(TextValorCusto133, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(TextValorCusto134, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus124, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(TextValorCusto144, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(LabelValorCus123, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(TextValorCusto143, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(LabelValorCus117, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)
                                            .addComponent(TextValorCusto137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelValorCus118, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(TextValorCusto138, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(LabelValorCus125, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(TextValorCusto145, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus127, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(TextValorCusto147, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus126, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(TextValorCusto146, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus128, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(TextValorCusto148, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus129, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(TextValorCusto149, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LabelValorCus130, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(TextValorCusto150, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LabelValorCus131, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelValorCus132)
                                            .addComponent(LabelValorCus49))
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TextValorCusto151, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboSelecionaTipoPesquisa11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(DateCadastro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabelValorCus134, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(TextValorCusto153, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelValorCus135, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TextValorCusto154, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("  Sindicato Detalhes  ", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 944, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPesquisar2ActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {           // adiciona as tabelas de acordo com a String selecionada no jComboBox
            //
            //            String terminal = jComboSelecionaTipoPesquisa.getSelectedItem() + ""; // transforma o jComboBox em uma String
            //            try {
                //                if (terminal.equals("Código")) {    // compara para ver se a String e o codigo
                    //                    if (!clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).isEmpty()) { //testa para ver se existem clientes com o cpodigo informado
                        //                        for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                            //                            model.addRow(new String[]{jTextPesquisar.getText() + "", clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getNome(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getLogradouro(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getT1(), clienteDAO.getCliente(Integer.parseInt(jTextPesquisar.getText() + "")).get(i).getStatus()});
                            //                        }
                        //                    } else {
                        //                        JOptionPane.showMessageDialog(null, "Não existem clientes com o código " + jTextPesquisar.getText() + " cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                        //                    }
                    //                }
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
                //
                //            }
            //            if (terminal.equals("Nome")) {
                //                if (!clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getCodigo() + "", clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getNome(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getLogradouro(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getT1(), clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //                }
                //                //clienteDAO.getCliente(jTextPesquisar.getText() + "", null, null).get(0).getCodigo();
                //            }
            //            if (terminal.equals("RG")) {
                //                if (!clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").isEmpty()) {
                    //                    System.out.println(clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome());
                    //
                    //                    model.addRow(new String[]{clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getCodigo() + "", clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getNome(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getLogradouro(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getT1(), clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "").get(0).getStatus()});
                    //
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o RG '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, null, jTextPesquisar.getText() + "");
                //            }
            //
            //            if (terminal.equals("CPF")) {
                //
                //                if (!clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null).isEmpty()) {
                    //                    for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                        //                        model.addRow(new String[]{clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getCodigo() + "", clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getNome(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getLogradouro(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getT1(), clienteDAO.getCliente(null,jTextPesquisar.getText() + "",null).get(i).getStatus()});
                        //                    }
                    //                } else {
                    //                    JOptionPane.showMessageDialog(null, "Não existem clientes com o CPF '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                    //
                    //                }
                //                //clienteDAO.getCliente(null, jTextPesquisar.getText() + "", null);
                //            }
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Não foi possível executar a pesquisa, por favor, rivise os dados e tente novamente!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        //        if (model.getRowCount() > 0) {
            //            while (model.getRowCount() > 0) {
                //                model.removeRow(0); // limpa a tabela
                //            }
            //        }
        //        try {
            //            if (!clienteDAO.getCliente("", null, null).isEmpty()) {
                //                for (int i = 0; i < clienteDAO.numeroLinhas; i++) {
                    //                    model.addRow(new String[]{clienteDAO.getCliente().get(i).getCodigo() + "", clienteDAO.getCliente().get(i).getNome(), clienteDAO.getCliente().get(i).getLogradouro(), clienteDAO.getCliente().get(i).getT1(), clienteDAO.getCliente().get(i).getStatus()});
                    //                }
                //            } else {
                //                JOptionPane.showMessageDialog(null, "Não existem clientes com o nome '" + jTextPesquisar.getText() + "' cadastrados!", "Erro", JOptionPane.WARNING_MESSAGE);
                //            }
            //        } catch (SQLException ex) {
            //            System.out.println(ex);
            //        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        //        this.jButtonNovo.setEnabled(false);
        //        this.ativaCampo();
        //        this.limpaCampo();
        //        this.jButtonGravar.setEnabled(true);
        //        this.setNovoCodigo();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //        this.ativaCampo();
        //        this.jButtonGravar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        //        String terminal = this.jComboGrupo.getSelectedItem() + "";
        //        char[] a = terminal.toCharArray();
        //        int posicao = 0;
        //        for (int i = 0; i < terminal.length(); i++) {
            //            if (a[i] == '-') {
                //                posicao = i;
                //            }
            //        }
        //        int codigoGrupo = Integer.parseInt(terminal.substring(0, posicao));
        //        try {
            //            if (subGrupoDAO.ContaCod(Integer.parseInt(jTextCodigo.getText())) == 0) {
                //                subGrupoDAO.setSubGrupo(jTextDescricao.getText() + "", codigoGrupo, subGrupoBean.getTentativas());
                //            } else {
                //                subGrupoDAO.atualizaSubGrupo(Integer.parseInt(jTextCodigo.getText()), jTextDescricao.getText() + "", codigoGrupo, subGrupoBean.getTentativas());
                //            }
            //            this.desativaCampo();
            //            this.jButtonGravar.setEnabled(false);
            //            this.jButtonNovo.setEnabled(true);
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ClienteNew.class.getName()).log(Level.SEVERE, null, ex);
            //            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos!", "Erro", JOptionPane.WARNING_MESSAGE);
            //        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravar1ActionPerformed

    private void TextValorCusto128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto128ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto128ActionPerformed

    private void TextValorCusto133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto133ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto133ActionPerformed

    private void TextValorCusto134ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto134ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto134ActionPerformed

    private void jButtonNovo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovo6ActionPerformed

    private void TextValorCusto137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto137ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto137ActionPerformed

    private void TextValorCusto138ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto138ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto138ActionPerformed

    private void TextValorCusto143ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto143ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto143ActionPerformed

    private void TextValorCusto144ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto144ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto144ActionPerformed

    private void TextValorCusto145ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto145ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto145ActionPerformed

    private void TextValorCusto146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto146ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto146ActionPerformed

    private void TextValorCusto147ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto147ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto147ActionPerformed

    private void TextValorCusto148ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto148ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto148ActionPerformed

    private void TextValorCusto149ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto149ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto149ActionPerformed

    private void TextValorCusto150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto150ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto150ActionPerformed

    private void TextValorCusto151ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto151ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto151ActionPerformed

    private void TextValorCusto152ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto152ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto152ActionPerformed

    private void TextValorCusto153ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto153ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto153ActionPerformed

    private void TextValorCusto154ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorCusto154ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorCusto154ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SindicatoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SindicatoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SindicatoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SindicatoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SindicatoNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateCadastro3;
    private javax.swing.JLabel LabelValorCus112;
    private javax.swing.JLabel LabelValorCus115;
    private javax.swing.JLabel LabelValorCus117;
    private javax.swing.JLabel LabelValorCus118;
    private javax.swing.JLabel LabelValorCus123;
    private javax.swing.JLabel LabelValorCus124;
    private javax.swing.JLabel LabelValorCus125;
    private javax.swing.JLabel LabelValorCus126;
    private javax.swing.JLabel LabelValorCus127;
    private javax.swing.JLabel LabelValorCus128;
    private javax.swing.JLabel LabelValorCus129;
    private javax.swing.JLabel LabelValorCus130;
    private javax.swing.JLabel LabelValorCus131;
    private javax.swing.JLabel LabelValorCus132;
    private javax.swing.JLabel LabelValorCus133;
    private javax.swing.JLabel LabelValorCus134;
    private javax.swing.JLabel LabelValorCus135;
    private javax.swing.JLabel LabelValorCus49;
    private javax.swing.JTextField TextValorCusto128;
    private javax.swing.JTextField TextValorCusto133;
    private javax.swing.JTextField TextValorCusto134;
    private javax.swing.JTextField TextValorCusto137;
    private javax.swing.JTextField TextValorCusto138;
    private javax.swing.JTextField TextValorCusto143;
    private javax.swing.JTextField TextValorCusto144;
    private javax.swing.JTextField TextValorCusto145;
    private javax.swing.JTextField TextValorCusto146;
    private javax.swing.JTextField TextValorCusto147;
    private javax.swing.JTextField TextValorCusto148;
    private javax.swing.JTextField TextValorCusto149;
    private javax.swing.JTextField TextValorCusto150;
    private javax.swing.JTextField TextValorCusto151;
    private javax.swing.JTextField TextValorCusto152;
    private javax.swing.JTextField TextValorCusto153;
    private javax.swing.JTextField TextValorCusto154;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonGravar1;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonNovo6;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboSelecionaTipoPesquisa11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableCliente1;
    private javax.swing.JTable jTableCliente2;
    private javax.swing.JTextField jTextPesquisar;
    private javax.swing.JTextField jTextPesquisar1;
    private javax.swing.JTextField jTextPesquisar2;
    // End of variables declaration//GEN-END:variables
}
